config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  delete "password", to: "passwords#destroy"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  delete "logout", to: "session#destroy"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets
  resources :registrations do
    member do
      get :confirm_email
    end
  end

  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: {minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hour.from_now
  end
  def published?
    tweet_id?
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_tweet, only: [:edit, :show, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet was updated successfuly!"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was  unscheduled!"
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "Successfuly scheduled a tweet!"
    else
      render :new    
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form|%>
  <%= render "shared/form_errors", form: form%>
  <div class= "mb-3">
    <%= form.label :twitter_account_id%>
    <%= form.collection_select :twitter_account_id , Current.user.twitter_accounts, :id , :username, {}, {class: "form-control"}%>
    <%= link_to "Connect your twitter account" , "/auth/twitter", method: :post%>
  </div>
  <div class= "mb-3">
    <%= form.label :body%>
    <%= form.text_area :body, class: "form-control"%>
  </div>
  <div class= "mb-3">
    <%= form.label :publish_at%>
    <div class= "form-control">
      <%=form.datetime_select :publish_at%>
    </div>
  </div>
  <%= form.button "Scheduled", class: "btn btn-primary"%>

  <% if form.object.persisted? %>
    <%= link_to "Delete", form.object, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"%>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>
  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle"%>
    <%= link_to "@#{tweet.twitter_account.name}","https://twitter.com/#{tweet.twitter_account.username}", target: :__blank%>
  </div>
  <% if tweet.published? %>
    <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :__blank%>
  <% else %>
    Scheduled for <%= l tweet.publish_at, format: :short%>
    <%= link_to "Edit Tweet", edit_tweet_path(tweet)%>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>
<%= render "form", tweet: @tweet%>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any?%>
    <%= link_to "Scheduled a tweet", new_tweet_path , class: "btn btn-primary"%>
  <% end %>
</div>

<% if Current.user.twitter_accounts.none?%>
  <%= link_to "Connect your Twitter account", "/auth/twitter", method: :post, class: "btn btn-primary"%>
<% end %>

<%= render @tweets%>

app/views/tweets/new.html.erb
<h1>Scheduled A Tweet</h1>
<%= render "form", tweet: @tweet%>